version: "3.9"

services:
  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      NGINX_CERT: ${NGINX_CERT}
      NGINX_CERT_KEY: ${NGINX_CERT_KEY}
    depends_on:
      - server
      - pgadmin

  server:
      container_name: prakticum-server
      image: ${GAME_IMAGE}
      restart: always
      ports:
          - "${SERVER_PORT}:${SERVER_PORT}"
      environment:
        VITE_ROOT_PATH: ${ROOT_PATH}
        VITE_GAME_URL: ${GAME_URL}
        VITE_BACKEND_URL: ${BACKEND_URL}
        SERVER_PORT: ${SERVER_PORT}
        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      depends_on:
        - postgres
      networks:
        - local

  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - local

  pgadmin:
    container_name: pgadmin
    user: root
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - /tmp/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - local

networks:
  local:
    driver: bridge
