name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
          cache-dependency-path: yarn.lock
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
