name: Deploy statics to GitHub Pages

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'sprint-*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: packages/client
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
          cache-dependency-path: yarn.lock

      - name: Install main deps
        run: yarn install --frozen-lockfile

      - name: Build
      - run: yarn build

      #      - run: yarn export
      #
      #      - name: Deploy
      #        id: deployment
      #        uses: peaceiris/actions-gh-pages@v3
      #        if: ${{ github.ref == 'refs/heads/main' }}
      #        with:
      #          github_token: ${{ secrets.GITHUB_TOKEN }}
      #          publish_dir: ./out

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
