name: Deploy statics to GitHub Pages

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - sprint*

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  REACT_APP_DEPLOY: GITHUB_PAGES

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
          cache-dependency-path: yarn.lock

      - name: Install main deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:client

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: packages/client/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
